<a href="https://colab.research.google.com/github/UsernameEnterausernameisnotavaible/Tugas-PKM-KC-FT-UPNVJ-2024/blob/main/xgboost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
data = pd.read_csv("df1 (9).csv")
data = data.drop(['Unnamed: 0'],axis=1)

# Split features and target variable


In [ ]:
data

Age  Experience        Income  Family       CCAvg  Education  Mortgage  \
0      25           1  6.429208e+07       4  25192000.0          1         0   
1      45          19  4.461083e+07       3  23617500.0          1         0   
2      39          15  1.443292e+07       1  15745000.0          1         0   
3      35           9  1.312083e+08       1  42511500.0          2         0   
4      35           8  5.904375e+07       4  15745000.0          2         0   
...   ...         ...           ...     ...         ...        ...       ...   
4995   29           3  5.248333e+07       1  29915500.0          3         0   
4996   30           4  1.968125e+07       4   6298000.0          1        85   
4997   63          39  3.149000e+07       2   4723500.0          3         0   
4998   65          40  6.429208e+07       3   7872500.0          2         0   
4999   28           4  1.089029e+08       3  12596000.0          1         0   

      Personal Loan  Securities Account  CD Account  Online  CreditCard  
0                 0                   1           0       0           0  
1                 0                   1           0       0           0  
2                 0                   0           0       0           0  
3                 0                   0           0       0           0  
4                 0                   0           0       0           1  
...             ...                 ...         ...     ...         ...  
4995              0                   0           0       1           0  
4996              0                   0           0       1           0  
4997              0                   0           0       0           0  
4998              0                   0           0       1           0  
4999              0                   0           0       1           1  

[5000 rows x 12 columns]

In [ ]:
X = data.drop(columns=["Personal Loan"])
y = data["Personal Loan"]


In [ ]:
x

NameError: name 'x' is not defined

In [ ]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Initialize XGBoost model
model = xgb.XGBClassifier()

# Train the model
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
missing_cols = set(X_train.columns) - set(X_test.columns)
for col in missing_cols:
    X_test[col] = 0

# Ensure the order of columns is the same
X_test = X_test[X_train.columns]

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
# Calculate precision
precision = precision_score(y_test, y_pred)

# Calculate recall
recall = recall_score(y_test, y_pred)

# Calculate F1-score
f1 = f1_score(y_test, y_pred)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.992
Precision: 0.970873786407767
Recall: 0.9523809523809523
F1-score: 0.9615384615384616
Confusion Matrix:
[[892   3]
 [  5 100]]


In [ ]:
X

Age  Experience        Income  Family       CCAvg  Education  Mortgage  \
0      25           1  6.429208e+07       4  25192000.0          1         0   
1      45          19  4.461083e+07       3  23617500.0          1         0   
2      39          15  1.443292e+07       1  15745000.0          1         0   
3      35           9  1.312083e+08       1  42511500.0          2         0   
4      35           8  5.904375e+07       4  15745000.0          2         0   
...   ...         ...           ...     ...         ...        ...       ...   
4995   29           3  5.248333e+07       1  29915500.0          3         0   
4996   30           4  1.968125e+07       4   6298000.0          1        85   
4997   63          39  3.149000e+07       2   4723500.0          3         0   
4998   65          40  6.429208e+07       3   7872500.0          2         0   
4999   28           4  1.089029e+08       3  12596000.0          1         0   

      Securities Account  CD Account  Online  CreditCard  
0                      1           0       0           0  
1                      1           0       0           0  
2                      0           0       0           0  
3                      0           0       0           0  
4                      0           0       0           1  
...                  ...         ...     ...         ...  
4995                   0           0       1           0  
4996                   0           0       1           0  
4997                   0           0       0           0  
4998                   0           0       1           0  
4999                   0           0       1           1  

[5000 rows x 11 columns]

In [ ]:
data

Age  Experience        Income  Family       CCAvg  Education  Mortgage  \
0      25           1  6.429208e+07       4  25192000.0          1         0   
1      45          19  4.461083e+07       3  23617500.0          1         0   
2      39          15  1.443292e+07       1  15745000.0          1         0   
3      35           9  1.312083e+08       1  42511500.0          2         0   
4      35           8  5.904375e+07       4  15745000.0          2         0   
...   ...         ...           ...     ...         ...        ...       ...   
4995   29           3  5.248333e+07       1  29915500.0          3         0   
4996   30           4  1.968125e+07       4   6298000.0          1        85   
4997   63          39  3.149000e+07       2   4723500.0          3         0   
4998   65          40  6.429208e+07       3   7872500.0          2         0   
4999   28           4  1.089029e+08       3  12596000.0          1         0   

      Personal Loan  Securities Account  CD Account  Online  CreditCard  
0                 0                   1           0       0           0  
1                 0                   1           0       0           0  
2                 0                   0           0       0           0  
3                 0                   0           0       0           0  
4                 0                   0           0       0           1  
...             ...                 ...         ...     ...         ...  
4995              0                   0           0       1           0  
4996              0                   0           0       1           0  
4997              0                   0           0       0           0  
4998              0                   0           0       1           0  
4999              0                   0           0       1           1  

[5000 rows x 12 columns]

In [ ]:
X = np.array([[34, 9 , 15	, 1 , 8.9 , 3 , 0 , 0 , 0 , 0 , 0 ]])
X = X.astype(float)


In [ ]:
y_pred = model.predict(X)
y_pred

array([0])

In [ ]:
import pickle

In [ ]:
data = { "model": model}
with open('saved_steps.pkl', 'wb') as file:
   pickle.dump(data,file)

In [ ]:

with open('saved_steps.pkl', 'rb') as file:
   data = pickle.load(file)

model_loaded = data["model"]

In [ ]:
model_loaded

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
model = jb.load('xgb_model.pkl')

In [ ]:
y_pred = model_loaded.predict(X)
y_pred

array([0])